# Generated by Django 5.0.6 on 2024-05-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EdenHill', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='title',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='users',
            name='description',
        ),
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
