# Generated by Django 5.0.6 on 2024-05-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdenHill', '0003_rename_firstname_users_name_alter_users_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='firstname',
        ),
    ]
